### ISSUE TITLE
Instal fails when installing with PHP 7.0 active

### ISSUE THREAD

**Issue by ntwb** [Chassis/Debugging#2]
`Error: Duplicate declaration: Package[php5-cli] is already declared in file /vagrant/puppet/modules/wp/manifests/cli.pp:54; cannot redeclare at /vagrant/puppet/modules/chassis/manifests/php.pp:106 on node vagrant.local
`

**Comment by BronsonQuick** [comment]
This is a temp bugfix for the Debugging issue: https://github.com/Chassis/Chassis/tree/debugging-extension-fix I feel it should be fixed upstream https://github.com/rmccue/puppet-wp.git as it doesn't account for Php 7.x. https://github.com/rmccue/puppet-wp/blob/master/manifests/cli.pp#L8 I'll have a chat to @rmccue about it today.

**Comment by BronsonQuick** [comment]
This should be fixed by this now: https://github.com/Chassis/Chassis/pull/282
